dist: trusty
sudo: false

language: rust
cache: cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly

env:
  - PKG_CONFIG_PATH="/usr/lib/*/pkgconfig/"

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages:
    - libsmbclient-dev
    - pkg-config
    - clang-3.9
    - libclang-3.9-dev

