dist: trusty
sudo: false

language: rust
cache: cargo
rust:
- stable
- beta
- nightly
matrix:
  allow_failures:
  - rust: nightly

env:
  global:
  - LIBCLANG_PATH="/usr/lib/llvm-3.9/lib"
  - PKG_CONFIG_PATH="/usr/lib/*/pkgconfig/"

addons:
  apt:
    sources:
    - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.9 main'
      key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages:
    - libsmbclient-dev
    - pkg-config
    - clang-3.9
    - libclang-3.9-dev
    - llvm-3.9-dev

notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/ab0b5f048023444e2080
    on_success: change
    on_failure: always
    on_start: never
